### PR TITLE
Refactor the calculation

### LINKED ISSUE #20: 32bit arithmetic comments
The Rust implementation is based off of the original paper, which included a C implementation: https://www.ietf.org/rfc/rfc1321.txt.

The paper was written in 1992, a time before 64 bit registers were widely available. The C code therefore splits the length of the message into two u32s, which then have manual arithmetic performed on them. The original source code includes comments around this arithmetic which have been omitted from the Rust implementation.

This issue is to help anyone who might be reading the code: 

```
let mut k = ((count[0] >> 3) & 0x3f) as usize;
let length = data.len() as u32;
count[0] = count[0].wrapping_add(length << 3);
if count[0] < length << 3 {
    count[1] = count[1].wrapping_add(1);
}
count[1] = count[1].wrapping_add(length >> 29);
```

and wondering what's going on.

The following comments should help future readers unfamiliar with this kind of arithmetic.

1. count[0] and count[1] represent the number of _bits_ of the input message in little-endian form (i.e. the memory layout of the little-endian 64bit number would be [count[0],count[1]]).
2. Bit shifts by 3 are used to transform this figure between a bytes count and a bits count.
3. The first line is computing the number of bytes modulo 64: first turn bits to bytes, then AND with 0x3f (63 in decimal) returns the number of bytes mod-64.
4. The first wrapping_add line is adding the length of the next chunk of message (in bits). If adding this extra length triggers a wrap (i.e. count[0] + length<<3 > 2^32-1 then we need to carry the add through to the upper 32 bit number (which is what the count[1].wrapping_add(1) is doing). wrapping_add is used here to take into account that the size of these numbers could be going above 64 bits in total.
5. Finally the last line is adding on the top-3 most significant bits from the original length to the count[1]. These weren't included when length << 3 was added to count[0] as they got chopped off by the left-shift.

Final note: given that we now have 64 bit integers freely available, this code could all be changed to u64.wrapping_add() style code. MD5 has been deprecated though, so there's little point.

### PR DESCRIPTION
**Pull request by tomhamiltonlambda**
Same PR as before except: 

1. No changes to tests or public APIs.
2. Since retaining context additional bit-twiddling is required, which has removed the performance gain. Performance is similar, or slightly faster (testing showed benchmarks times are about 97% of previous ones - i.e. ~ 3% faster).

Tests all pass

Closes #20.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Wait, wait. Let us look into this. From 20% to 3% is quite a difference. I wonder what it is that causes this slowdown.

**Comment by tomhamiltonlambda** [comment]
Ok - I'll check when I have time.

**Comment by tomhamiltonlambda** [comment]
I've narrowed it down to a performance penalty for using indirection with Context. See this diff: https://www.diffchecker.com/O1QPYnOD/

The code on the left (where buffer, state and count are wrapped up in a Context struct) performs about 20% slower than the code on the right - where I just define the individual variables outside of a struct.

I'm checking the compiled code on CompilerExplorer and it looks like there's more inlining done in the faster code. I'll try to go through the assembly to see what the fundamental difference is here. Seems very odd.

**Comment by IvanUkhov** [comment]
Uh, nice detective work! It is unexpected. Perhaps one could try to bind locally the used fields from Context.

**Comment by tomhamiltonlambda** [comment]
I've spent more time trying to determine the root cause of performance differences - it's a bit of a minefield, with most changes generating very similar underlying code. I decided the best way forwards would be to do the simplest merge between my original fast code and the desired structure.

In the latest commit there are two branches of computation. If you create a Context and call .consume, .compute it goes down one path, explicitly using the Context struct etc. If you have all the data in memory and just call compute(data) then it goes down another path (20% faster). 

The best explanation that I can see for the speed improvement is that under the fast-path there's more inlining/unrolling. When I manually inlined the compute(data) path with Context style code the resulting compute function was about 400 lines of assembly, the faster version (which doesn't rely on the Context struct) is about 600 lines in assembly.

So the good news is that the benchmarks have gone from about 1.7 to 1.3, and that the existing tests cover both calculation paths already.

**Comment by IvanUkhov** [comment]
Thank you! Pushed a few cosmetic adjustments and also removed code publication. Please confirm that you are still seeing the performance speed up.

**Comment by tomhamiltonlambda** [comment]
Just ran the benchmarks and they're still at 1.3 cf previously 1.7 - so your refactors haven't affected the improved performance. Thanks for your help getting it through!

**Comment by IvanUkhov** [comment]
Thank you!

**Comment by IvanUkhov** [comment]
Managed to reduce the time even further and also make the two versions produce the same performance:

https://github.com/stainless-steel/md5/actions/runs/8870083200/job/24351481311

**Comment by IvanUkhov** [comment]
No, sorry. False alarm.

**Pull request merged**
