### PR TITLE
Implement Debug and Hash traits for Digest

### PR DESCRIPTION
**Pull request by yosefdi**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
What is the reason we need a custom implementation of `Debug`?

**Comment by yosefdi** [comment]
The default implementation of Debug would dump 16 byte array, like [ 20, 45, 182, ...
This is not pretty. Better to see upper hex in debug traces.

**Comment by IvanUkhov** [comment]
Yeah, but now we have to decide which one to use: `LowerHex` or `UpperHex`. Do you mind keeping the default implementation for now?

**Comment by yosefdi** [comment]
I think we better choose between LowerHex and UpperHex, rather than taking representation that is clearly the worse between these alternatives.

**Comment by IvanUkhov** [comment]
The idea behind deriving `Debug`, even though the print-out might not be exactly user friendly, is to make it possible to debug-print structures that contain `Digest`.

**Comment by yosefdi** [comment]
Yes, but we know that nature of md5 hash better than underlying 16 byte array. The default representation for u8 array is a JSON-like array, just because at this level there is no additional knowledge of how it should look otherwise. In digest we know that people who debug the code would like to see hexadecimal digests. Overriding default looks to me very much justified.

**Comment by yosefdi** [comment]
I would even consider having overridden implementation for Hash trait. As we know it is md5 hash, may it be better to implement Hash as xor between low and high 8 bytes, instead the default implementation, whatever it is?

**Comment by IvanUkhov** [comment]
All right, let’s override then. It seems that, in the Rust/Cargo ecosystem, we generally tend to use lowercase hashes, and this is how it’s been in this crate as well. I vote for `LowerHex`.

**Comment by yosefdi** [comment]
That is absolutely fine. Let make it LowerHex

**Comment by IvanUkhov** [comment]
Thank you!

**Pull request merged**
