### PR TITLE
Derive PartialEq, Eq, Copy & Clone for Digest

### PR DESCRIPTION
**Pull request by sethdusek**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thanks! Could you please sort them alphabetically?

**Comment by IvanUkhov** [comment]
Thank you!

**Comment by IvanUkhov** [comment]
@SethDusek, I’d like to add your name to the authors list in `Cargo.toml`. Am I right that your name is Seth Dusek?

**Comment by sethdusek** [comment]
No that is just an alias. My real name is Kamal Ahmad if you would like to include it however.

**Pull request merged**
